/*
 * Copyright © 2011 James Simmons 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Authors:
 *	James Simmons <jsimmons@infradead.org>
 */

#include "drmP.h"
#include "drm.h"
#include "drm_crtc.h"
#include "drm_crtc_helper.h"

#include "crtc_hw.h"
#include "chrome_drv.h"

/*
 * Routines for controlling stuff on the analog port
 */
static const struct drm_encoder_funcs chrome_analog_enc_funcs = {
	.destroy = drm_encoder_cleanup,
};

/* Power down the DAC */
static void
chrome_analog_dpms(struct drm_encoder *encoder, int mode)
{
	struct drm_crtc *crtc = encoder->crtc;
	struct drm_chrome_private *dev_priv;
	struct chrome_crtc *iga;
	u8 dacmode;

	dev_priv = encoder->dev->dev_private;
	iga = &dev_priv->iga[0];
	if (crtc != &iga->crtc)
		iga = &dev_priv->iga[1];
	dacmode = crtc_inb(iga->vga_regs, 0x36);

	switch (mode) {
	case DRM_MODE_DPMS_SUSPEND:
		dacmode |= 0x20;	// VSync off  
		break;
	case DRM_MODE_DPMS_STANDBY:
		dacmode |= 0x10;	// HSync off	
		break;
	case DRM_MODE_DPMS_OFF:
		dacmode |= 0x30;	// HSync and VSync off
		break;
	case DRM_MODE_DPMS_ON:
	default:
		dacmode &= ~0x30;
		break;
	}

	crtc_outb(iga->vga_regs, 0x36, (dacmode & 0x30));
}

/* Pass our mode to the connectors and the CRTC to give them a chance to
 * adjust it according to limitations or connector properties, and also
 * a chance to reject the mode entirely. Usefule for things like scaling.
 */
static bool
chrome_analog_mode_fixup(struct drm_encoder *encoder,
		 struct drm_display_mode *mode,
		 struct drm_display_mode *adjusted_mode)
{
	/* Could sometimes be 8 */
	adjusted_mode->hdisplay = (adjusted_mode->hdisplay + 15) & ~15;

	drm_mode_set_crtcinfo(adjusted_mode, 0);
	return true;
}

static void
chrome_encoder_prepare(struct drm_encoder *encoder)
{
}

static void
chrome_encoder_commit(struct drm_encoder *encoder)
{
}

static void
chrome_analog_mode_set(struct drm_encoder *encoder,
		       struct drm_display_mode *mode,
		       struct drm_display_mode *adjusted_mode)
{
}

static const struct drm_encoder_helper_funcs chrome_analog_enc_helper_funcs = {
	.dpms = chrome_analog_dpms,
	.mode_fixup = chrome_analog_mode_fixup,
	.prepare = chrome_encoder_prepare,
	.commit = chrome_encoder_commit,
	.mode_set = chrome_analog_mode_set,
};

static enum drm_connector_status
chrome_analog_detect(struct drm_connector *connector, bool force)
{
	struct drm_device *dev = connector->dev;

	//if (drm_do_probe_ddc_edid(connector))
		return connector_status_connected;

	return connector_status_unknown;
}

static void
chrome_analog_destroy(struct drm_connector *connector)
{
	//chrome_i2c_destroy(connector->dev, DRM_MODE_CONNECTOR_VGA);
	drm_sysfs_connector_remove(connector);
	drm_connector_cleanup(connector);
	kfree(connector);
}

static int
chrome_analog_set_property(struct drm_connector *connector,
		  struct drm_property *property,
		  uint64_t value)
{
	struct drm_device *dev = connector->dev;

	if (property == dev->mode_config.dpms_property && connector->encoder)
		chrome_analog_dpms(connector->encoder, (uint32_t)(value & 0xf));
	return 0;
}

static const struct drm_connector_funcs chrome_analog_connector_funcs = {
	.detect = chrome_analog_detect,
	.fill_modes = drm_helper_probe_single_connector_modes,
	.destroy = chrome_analog_destroy,
	.set_property = chrome_analog_set_property,
};

/* This function test if the drm_display_modes generated by a display
 * monitor that is connected is supported by the graphics card.
 */
static int
chrome_analog_mode_valid(struct drm_connector *connector,
			struct drm_display_mode *mode)
{
	//struct drm_device *dev = connector->dev;

	if ((mode->flags & DRM_MODE_FLAG_INTERLACE) &&
	    !connector->interlace_allowed)
		return MODE_NO_INTERLACE;

	return MODE_OK;
}

static struct drm_encoder* 
chrome_best_encoder(struct drm_connector *connector)
{
	struct drm_device *dev = connector->dev;
	struct drm_chrome_private *dev_priv = dev->dev_private;

	/* Only one encoder i.e DAC for connector */
	return NULL; //dev_priv->best;
}

static const struct drm_connector_helper_funcs chrome_analog_connector_helper_funcs = {
	.mode_valid = chrome_analog_mode_valid,
	.get_modes = chrome_get_modes,
	.best_encoder = chrome_best_encoder,
};

void chrome_analog_init(struct drm_device *dev)
{
	struct drm_chrome_private *dev_priv = dev->dev_private;
	struct drm_connector *connector;
	struct drm_encoder *enc;
	void *par;
	int size;

	/* Set up the I2C bus. */
	if (chrome_encoder_probe(dev, 0, dev_priv->iga[0].vga_regs+0x04, 0x26)) {
		DRM_ERROR("I2C bus registration failed.\n");
		return;
	}

	size = sizeof(struct drm_encoder) + sizeof(struct drm_connector);
	par = kzalloc(size, GFP_KERNEL);
	if (!par) {
		DRM_ERROR("Failed to allocate connector and encoder\n");
		return;
	}
	connector = par + sizeof(struct drm_encoder);
	enc = par;

	/* Piece together our connector */
	drm_connector_init(dev, connector, &chrome_analog_connector_funcs,
				DRM_MODE_CONNECTOR_VGA);
	drm_connector_helper_add(connector, &chrome_analog_connector_helper_funcs);

	connector->interlace_allowed = true;
	connector->doublescan_allowed = true;

	/* Setup the encoders and attach them */
	drm_encoder_init(dev, enc, &chrome_analog_enc_funcs, DRM_MODE_ENCODER_DAC);
	drm_encoder_helper_add(enc, &chrome_analog_enc_helper_funcs);
	//dev_priv->best = enc;
	enc->possible_clones = 1; //clone_mask;
	enc->possible_crtcs = 1; //crtc_mask;

	drm_mode_connector_attach_encoder(connector, enc);

	drm_sysfs_connector_add(connector);
}
